// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ejmjukrfpdpgkxdwgoax.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVqbWp1a3JmcGRwZ2t4ZHdnb2F4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDIxNTE0OTIsImV4cCI6MjA1NzcyNzQ5Mn0.QiyEyUS7bK9gFCtETpL4jWY_47t1Rrv1k6VKgsbiRp8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);